export const statusCatalog = [
  { code: '1', replace: 'VL1', description: 'Success' },
  { code: '101', replace: 'IN1', description: 'The account information is incorrect. Please verify the account details.' },
  { code: '102', replace: 'IN2', description: 'Make sure that the beneficiary name provided is entered exactly as it appears on their account in {Wallet/Bank/VPA Name}' },
  { code: '103', replace: 'IN3', description: 'The receiver exceeds the transaction limit. Please try a different delivery method.' },
  { code: '104', replace: 'IN4', description: 'The receiver exceeds the transaction amount limit. Please enter a smaller amount.' },
  { code: '105', replace: 'IN5', description: 'The receiver exceeds the annual transaction count limit. Please try a different delivery method.' },
  { code: '106', replace: 'IN6', description: 'The receiver exceeds the annual transaction amount limit. Please try a different delivery method.' },
  { code: '107', replace: 'IN7', description: 'The receiver exceeds the monthly transaction count limit. Please try a different delivery method.' },
  { code: '108', replace: 'IN8', description: 'The receiver exceeds the monthly transaction amount limit. Please try a different delivery method.' },
  { code: '109', replace: 'IN9', description: 'The receiver exceeds the daily transaction count limit. Please try a different delivery method.' },
  { code: '110', replace: 'IN10', description: 'The receiver exceeds the daily transaction amount limit. Please try a different delivery method.' },
  { code: '111', replace: 'IN11', description: 'The receiver\'s account balance is full. Please enter a smaller amount.' },
  { code: '112', replace: 'ER1', description: 'Something went wrong. Please try again later.' },
  { code: '113', replace: 'IN13', description: 'The customer exceeds the transaction limit. Please try a different delivery method.' },
  { code: '114', replace: 'IN14', description: 'The customer exceeds the transaction amount limit. Please try a different delivery method.' },
  { code: '115', replace: 'IN15', description: 'The customer exceeds the annual transaction count limit. Please try a different delivery method.' },
  { code: '116', replace: 'IN16', description: 'The customer exceeds the annual transaction amount limit. Please try a different delivery method.' },
  { code: '117', replace: 'IN17', description: 'The customer exceeds the monthly transaction count limit. Please try a different delivery method.' },
  { code: '118', replace: 'IN18', description: 'The customer exceeds the monthly transaction amount limit. Please try a different delivery method.' },
  { code: '119', replace: 'IN19', description: 'The customer exceeds the daily transaction count limit. Please try a different delivery method.' },
  { code: '120', replace: 'IN20', description: 'The customer exceeds the daily transaction amount limit. Please try a different delivery method.' },
  { code: '121', replace: 'IN21', description: 'The receiver\'s account is locked or suspended. Please try a different delivery method.' },
  { code: '122', replace: 'IN22', description: 'The receiver\'s account is not active. Please try a different delivery method.' },
  { code: '123', replace: 'IN23', description: 'This account is not fully set up. Please instruct the customer to contact the receiver to complete the registration.' },
  { code: '124', replace: 'IN24', description: 'This account does not exist. Please verify with the customer.' },
  { code: '125', replace: 'IN25', description: 'The validation for this service has failed. Please try a different delivery method.' },
  { code: '126', replace: 'IN26', description: 'The receiver name entered \'{0}\' does not match with the receiver name on file \'{1}\'. The transaction cannot be completed with the receiver name provided. Would you like to continue and replace the receiver name with \'{1}\'?' },
  { code: '127', replace: 'IN27', description: 'The routing code/BIC is invalid. Please verify with the customer.' },
  { code: '128', replace: 'IN28', description: 'The sending currency does not match the account currency. Please verify with the customer.' },
  { code: '129', replace: 'IN29', description: 'The receiver name entered \'{0}\' does not match with the registered receiver name: \'{1}\'. Please verify with the customer.' },
  { code: '130', replace: 'IN30', description: 'The beneficiary\'s registered ID type on the account is not eligible for international remittances.' },
  { code: '131', replace: 'IN31', description: 'Invalid Transfer Reason. Please verify with the customer' },
  { code: '132', replace: 'IN32', description: 'The name you entered differs from the registered name from this account. You entered: {0}  Did you mean: {1}' },
  { code: '133', replace: 'IN33', description: 'The name you entered \'{0}\' doesn\'t match the registered name for this account. If the details are wrong, your money could go to the wrong person.' },
  { code: '134', replace: 'IN34', description: 'We couldn\'t confirm that this account belongs your recipient \'{0}\'. If the details are wrong, your money could go to the wrong person.' },
  { code: '154', replace: 'ER3', description: 'No Validation Performed' },
]
