export const statusCatalog = [
  { code: '1', description: 'Success' },
  { code: '112', description: 'Something went wrong. Please try again later.' },
  { code: '154', description: 'No Validation Performed' },
  { code: '101', description: 'The account information is incorrect. Please verify the account details.' },
  { code: '102', description: 'Make sure that the beneficiary name provided is entered exactly as it appears on their account in {Wallet/Bank/VPA Name}' },
  { code: '103', description: 'The receiver exceeds the transaction limit. Please try a different delivery method.' },
  { code: '104', description: 'The receiver exceeds the transaction amount limit. Please enter a smaller amount.' },
  { code: '105', description: 'The receiver exceeds the annual transaction count limit. Please try a different delivery method.' },
  { code: '106', description: 'The receiver exceeds the annual transaction amount limit. Please try a different delivery method.' },
  { code: '107', description: 'The receiver exceeds the monthly transaction count limit. Please try a different delivery method.' },
  { code: '108', description: 'The receiver exceeds the monthly transaction amount limit. Please try a different delivery method.' },
  { code: '109', description: 'The receiver exceeds the daily transaction count limit. Please try a different delivery method.' },
  { code: '110', description: 'The receiver exceeds the daily transaction amount limit. Please try a different delivery method.' },
  { code: '111', description: 'The receiver\'s account balance is full. Please enter a smaller amount.' },
  { code: '112', description: 'Something went wrong. Please try again later.' },
  { code: '113', description: 'The customer exceeds the transaction limit. Please try a different delivery method.' },
  { code: '114', description: 'The customer exceeds the transaction amount limit. Please try a different delivery method.' },
  { code: '115', description: 'The customer exceeds the annual transaction count limit. Please try a different delivery method.' },
  { code: '116', description: 'The customer exceeds the annual transaction amount limit. Please try a different delivery method.' },
  { code: '117', description: 'The customer exceeds the monthly transaction count limit. Please try a different delivery method.' },
  { code: '118', description: 'The customer exceeds the monthly transaction amount limit. Please try a different delivery method.' },
  { code: '119', description: 'The customer exceeds the daily transaction count limit. Please try a different delivery method.' },
  { code: '120', description: 'The customer exceeds the daily transaction amount limit. Please try a different delivery method.' },
  { code: '121', description: 'The receiver\'s account is locked or suspended. Please try a different delivery method.' },
  { code: '122', description: 'The receiver\'s account is not active. Please try a different delivery method.' },
  { code: '123', description: 'This account is not fully set up. Please instruct the customer to contact the receiver to complete the registration.' },
  { code: '124', description: 'This account does not exist. Please verify with the customer.' },
  { code: '125', description: 'The validation for this service has failed. Please try a different delivery method.' },
  { code: '126', description: 'The receiver name entered \'{0}\' does not match with the receiver name on file \'{1}\'. The transaction cannot be completed with the receiver name provided. Would you like to continue and replace the receiver name with \'{1}\'?' },
  { code: '127', description: 'The routing code/BIC is invalid. Please verify with the customer.' },
  { code: '128', description: 'The sending currency does not match the account currency. Please verify with the customer.' },
  { code: '129', description: 'The receiver name entered \'{0}\' does not match with the registered receiver name: \'{1}\'. Please verify with the customer.' },
  { code: '130', description: 'The beneficiary\'s registered ID type on the account is not eligible for international remittances.' },
]
